hyperskill_project:
  id: 83
  ide_files: https://cogniterra.org/media/attachments/lesson/24501/additional_files.json
  is_template_based: false
  use_ide: true
update_date: "Tue, 12 Dec 2023 17:33:45 UTC"
stages:
  - id: 457
    step: 7486
    is_completed: true
  - id: 458
    step: 7487
    is_completed: true
  - id: 459
    step: 7488
    is_completed: true
  - id: 460
    step: 7489
    is_completed: false
  - id: 461
    step: 7490
    is_completed: false
  - id: 462
    step: 7491
    is_completed: false
  - id: 463
    step: 7492
    is_completed: false
topics:
  0:
    - title: Introduction to Kotlin
      theory_id: 4350
    - title: "Basic literals: numbers, strings and characters"
      theory_id: 4351
    - title: Writing first program
      theory_id: 4362
    - title: Values and variables
      theory_id: 4371
    - title: Constants and val variables
      theory_id: 17408
    - title: Data types
      theory_id: 4388
    - title: Properties of basic types
      theory_id: 4455
    - title: Type conversion
      theory_id: 4672
    - title: Comments
      theory_id: 4406
    - title: Kotlin style guide. Coding conventions
      theory_id: 4419
    - title: Naming variables
      theory_id: 4389
    - title: Standard output
      theory_id: 4425
    - title: Invoking functions
      theory_id: 4575
    - title: Standard input with Java Scanner
      theory_id: 4445
    - title: Reading data with readln
      theory_id: 11224
  1:
    - title: String basics
      theory_id: 12553
    - title: String templates
      theory_id: 4547
    - title: Boolean type and operations. True and false
      theory_id: 4515
    - title: Arithmetic operations
      theory_id: 4472
    - title: "When different types meet: type coercion"
      theory_id: 9506
    - title: Increment and decrement
      theory_id: 10776
    - title: Integers in action
      theory_id: 4488
    - title: Comparing numbers. Relational operators
      theory_id: 4525
    - title: If expression
      theory_id: 4625
  2:
    - title: Command line overview
      theory_id: 8977
    - title: Parameters and options
      theory_id: 9746
    - title: "Loops: repeat statement"
      theory_id: 4643
    - title: Unicode
      theory_id: 7899
    - title: Characters. Char type
      theory_id: 4680
    - title: Ranges
      theory_id: 4633
    - title: Introduction to MutableList
      theory_id: 14879
    - title: For loop and ranges
      theory_id: 4652
    - title: IntelliJ IDEA
      theory_id: 37202
    - title: IntelliJ IDEA run configurations
      theory_id: 10630
  3:
    - title: Declaring functions
      theory_id: 4580
    - title: Errors in programs
      theory_id: 11559
    - title: Objects and their properties
      theory_id: 11233
    - title: Structural vs referential equality
      theory_id: 11236
    - title: Work with MutableLists
      theory_id: 14902
    - title: For loop and lists
      theory_id: 15022
    - title: Introduction to collections
      theory_id: 10390
    - title: Map
      theory_id: 12659
    - title: Mutable Map
      theory_id: 15876
    - title: Exception
      theory_id: 7243
    - title: Hierarchy of exceptions
      theory_id: 13264
    - title: Taming exceptions
      theory_id: 7601
    - title: Try-catch statement
      theory_id: 10622
    - title: The try-catch-finally statement
      theory_id: 11809
  4:
    - title: Functions as objects
      theory_id: 5991
    - title: Lambda expressions
      theory_id: 30148
    - title: Files
      theory_id: 13025
    - title: Reading files
      theory_id: 6351
    - title: Writing files
      theory_id: 9710
    - title: Random
      theory_id: 11801
    - title: Floating-point types
      theory_id: 4502
    - title: The Math library
      theory_id: 12532
  5:
    - title: List
      theory_id: 10730
    - title: Mutable List
      theory_id: 11032
  6:
    - title: Computer algorithms
      theory_id: 16547
    - title: "Big O: how to count it"
      theory_id: 35901
    - title: "Best, average and worst cases"
      theory_id: 20084
    - title: Data structures
      theory_id: 16927
    - title: Pseudocode
      theory_id: 15090
    - title: Pseudocode basics
      theory_id: 19510
    - title: Complex constructions in pseudocode
      theory_id: 20922
    - title: Stack
      theory_id: 5252
    - title: Nullable and non-nullable types
      theory_id: 7613
    - title: Type system
      theory_id: 9689
    - title: While loops
      theory_id: 4659
    - title: What is object-oriented programming
      theory_id: 3614
    - title: Declaring classes
      theory_id: 6200
    - title: When expression
      theory_id: 4631
    - title: Functional decomposition
      theory_id: 12668
    - title: Default arguments
      theory_id: 4637
    - title: Named arguments
      theory_id: 4640
    - title: Constructors
      theory_id: 10740
    - title: Member functions
      theory_id: 6364
    - title: Secondary constructor
      theory_id: 10746
    - title: Working with strings
      theory_id: 12561
    - title: Arrays
      theory_id: 4564
    - title: String arrays
      theory_id: 11477
    - title: Call stack
      theory_id: 11550
    - title: Scopes
      theory_id: 17116
    - title: Inheritance
      theory_id: 9844
    - title: Inheritance
      theory_id: 7770
    - title: Polymorphism
      theory_id: 10027
    - title: Overriding functions
      theory_id: 7884
    - title: toString()
      theory_id: 10193
    - title: Data class
      theory_id: 8526
    - title: The main() function
      theory_id: 10484
    - title: Avoiding NPEs. Null safety
      theory_id: 7619
